# Generated by Django 5.1.1 on 2024-09-26 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('business_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(blank=True, choices=[('invest', 'Investment'), ('IT', 'Information Technology'), ('cap', 'Capital Construction'), ('exp', 'Expenses'), ('service', 'Service')], max_length=30, null=True)),
                ('manager', models.CharField(blank=True, max_length=30, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_finish', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('number', models.CharField(blank=True, max_length=300, null=True)),
                ('client', models.CharField(blank=True, max_length=300, null=True)),
                ('contractor', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(blank=True, max_length=300, null=True)),
                ('scope', models.CharField(blank=True, max_length=300, null=True)),
                ('sign_off_date', models.DateField(blank=True, null=True)),
                ('lifecycle', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, choices=[('NEW', 'New'), ('DFT', 'Draft'), ('WIP', 'Work in progress'), ('CLO', 'Closed')], max_length=20, null=True)),
                ('manager', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.CharField(blank=True, max_length=300, null=True)),
                ('budget', models.CharField(blank=True, max_length=300, null=True)),
                ('cost_code', models.CharField(blank=True, max_length=30, null=True)),
                ('milestones', models.CharField(blank=True, max_length=300, null=True)),
                ('addendum', models.CharField(blank=True, max_length=300, null=True)),
                ('reference', models.CharField(blank=True, max_length=300, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contract.project')),
            ],
        ),
    ]
